### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by andreinedl** [qdsteam/sampmodmobile#1]
Hello,how i can build this .so file?From my ndk-build results the libd3d9.so

**Comment by Nika9911** [comment]
Looking forward to the update

**Comment by alyn-dev** [comment]
andrey da mi add pe dis bro ALYN.ADV#0001

**Comment by alyn-dev** [comment]
te ajut eu

**Comment by andreinedl** [comment]
> te ajut eu

A cam trecut 1 an, am rezolvat de mult timp =))

**Comment by alyn-dev** [comment]
da mi add sa mai vb


lun., 17 aug. 2020, 00:28 AndreySK4 <notifications@github.com> a scris:
